apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
  namespace: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app  
  strategy: {}
  template:
    metadata:
      labels:
        app: app
    spec:
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: "has-ssd"
      #               operator: In
      #               values: ["true"]
      containers:
        - name: labs
          image: micheldiasdocker/labs:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: "/"
              port: 3000
            initialDelaySeconds: 30
          livenessProbe:
            httpGet:
              path: "/healthz"
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 2
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "100m"
              memory: "256Mi"
      imagePullSecrets:
        - name: regcred
status: {}