apiVersion: v1
kind: ResourceQuota
metadata:
  name: app-quota
  namespace: app
spec:
  hard:
    requests.cpu: '2'
    requests.memory: 4Gi
    limits.cpu: '2'
    limits.memory: 4Gi
    pods: '10'
    persistentvolumeclaims: '5'
    requests.storage: 5Gi