apiVersion: v1
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImJXbGphR1ZzWkdsaGMyUnZZMnRsY2pveU5qYzVNekV6TkRnNE5FMXdRQT09IgoJCX0KCX0KfQ==
kind: Secret
metadata:
  name: regcred
  namespace: app
type: kubernetes.io/dockerconfigjson

